### ISSUE TITLE
Any chance to do Nyan Cat?

### ISSUE THREAD

**Issue by RichiH** [MacroPower/prometheus_video_renderer#1]
https://www.youtube.com/watch?v=QH2-TGUlwu4 might be a challenge because colors, but would be awesome.

**Comment by MacroPower** [comment]
Not sure how you could make this look good in the Prometheus UI, besides maybe going frame by frame and tracing all the color boundaries in black or something.

One possibility is to add an additional label and then you could set the color there, then generate a Grafana dashboard with overrides set so that {c="ff0000"} => red for instance. It'd mean a lot more series but ... I mean nyan cat doesn't exactly have that many frames so, I think it could be doable. Would this be acceptable @RichiH? 😄

**Comment by RichiH** [comment]
Sounds good!

If you do it in Grafana, I will get you a guest spot on our blog to write
about it.

Sent by mobile; please excuse my brevity.

**Comment by MacroPower** [comment]
@RichiH I found a Nyan Cat video that used the CGA color palette and it actually looks pretty good (in my opinion) in the Prometheus UI. Take a look: https://www.youtube.com/watch?v=qPG_HaZPGXA

I would still like to have a go at this in Grafana because I think I've discovered a pretty cool way of doing it. And if I'm able to get something decent, I would love to write about it. Will keep you posted!

**Comment by RichiH** [comment]
Nice! Correct colors pretty area should be easier in Grafana than in
Prometheus, if still fiddly.

FYI, we're amplifying this on Twitter, but I don't think you have an
account there.

Sent by mobile; please excuse my brevity.

**Comment by MacroPower** [comment]
Thanks for letting me know! I do have [@0xMacro](https://twitter.com/0xMacro) but normally I only use it because... well... my retirement is overexposed to random tweets from Elon Musk, to be honest.

**Comment by MacroPower** [comment]
@RichiH I just merged in some code that adds color support with Grafana. I think it looks really good!

Example video: https://www.youtube.com/watch?v=aLvh0oId3Go

![](https://raw.githubusercontent.com/MacroPower/prometheus_video_renderer/main/docs/img/rgb_grafana.png)

So I should be able to render your Nyan Cat via this method and close this issue sometime in the next few days. 🙂

**Comment by RichiH** [comment]
Nice! It already made the rounds within Grafana Labs.

If render time was lower, Doom would be within our grasp :)

**Comment by MacroPower** [comment]
@RichiH Haha, I had that exact same thought! With less series / "pixels", plus maybe the new time series panel (seems to go a lot faster in my limited testing), maybe something like that would be possible. Even at like 1fps it would make me very happy. Doing input without installing plugins might be challenging though.

**Comment by RichiH** [comment]
CC @marcusolsson

**Comment by MacroPower** [comment]
@RichiH It is complete: https://www.youtube.com/watch?v=G00cNxzqAD8 (watch in 4k for better color)

Hopefully the wait was worth it, ended up getting audio in there as well. 🙂

**Comment by MacroPower** [comment]
Also in case you're interested, moving everything to Grafana 8 improved render times by over 2x. Plus the UI responsiveness actually holds up really, really well with all the metrics loaded up. (Kudos to you guys on that!) 

I also ended up writing a small sdk + cli to help with rendering @ [MacroPower/grafana-image-renderer-sdk-go](https://github.com/MacroPower/grafana-image-renderer-sdk-go). (You can do time-lapses too which is pretty cool.) When you fully utilize Grafana 8 + an image renderer cluster via this cli (with cluster size matched to max concurrency), the amount of time it takes to actually render things out is way, way better. The Nyan Cat video was 6504 frames, and they all completed in 5189 seconds which is something like 20x faster than before.

**Comment by RichiH** [comment]
I never thought I would see something like this. Thank you!

**Comment by MacroPower** [comment]
I'm glad you like it. 🙂 Closing!
